// Generated by CoffeeScript 1.3.3
(function() {
  var L, core, root, _ref;

  root = typeof global !== "undefined" && global !== null ? global : window;

  root.root = root;

  L = {};

  root.lemur = L;

  core = L.core = {};

  (function() {
    var toString;
    toString = Object.prototype.toString;
    return core.to_type = function(o) {
      var s;
      s = toString.call(o);
      s = s.substring(8, s.length - 1);
      return s.toLowerCase();
    };
  })();

  core.s_trim = (_ref = String.prototype.trim) != null ? _ref : function() {
    return String(this).replace(/^\s+/, '').replace(/\s+$/, '');
  };

  (function() {
    var Noop, _ref1;
    Noop = function() {};
    return core.clone = (_ref1 = Object.create) != null ? _ref1 : function(o) {
      Noop.prototype = o;
      return new Noop();
    };
  })();

  if ((typeof exports !== "undefined" && exports !== null) && (typeof module !== "undefined" && module !== null)) {

  } else if (typeof provide !== "undefined" && provide !== null) {
    provide("lemur", L);
  }

}).call(this);
