// Generated by CoffeeScript 1.3.3
(function() {
  var C, L, p, puts, v;

  try {
    require('../');
  } catch (_error) {}

  L = lemur;

  C = L.compiler;

  puts = p = console.log.bind(console);

  v = new C.Var("->s");

  p(v.compile());

}).call(this);
