// Generated by CoffeeScript 1.3.3
(function() {
  var L;

  L = lemur;

  L.Compiler = (function() {

    function Compiler(_arg) {
      this.predefined = _arg.predefined, this.dependant_context = _arg.dependant_context;
    }

    return Compiler;

  })();

}).call(this);
